// Original, uncompressed exports. Images go through next/image, which
// serves sized AVIF/WebP derivatives; videos stream as static files.
export const M = {
  'ds-board': {
    src: '/media/design-system.png',
    w: 1672,
    h: 941,
    type: 'image',
  },
  'home-unpaid': {
    src: '/media/home-unpaid.png',
    w: 1125,
    h: 13523,
    type: 'image',
  },
  'home-paid': {
    src: '/media/home-paid.png',
    w: 1125,
    h: 11825,
    type: 'image',
  },
  experience: {
    src: '/media/experience.png',
    w: 1125,
    h: 13976,
    type: 'image',
  },
  syllabus: {
    src: '/media/syllabus.png',
    w: 1128,
    h: 13953,
    type: 'image',
  },
  'price-six': {
    src: '/media/price-six.png',
    w: 1125,
    h: 8384,
    type: 'image',
  },
  'search-entry': {
    src: '/media/search-entry.png',
    w: 1125,
    h: 4164,
    type: 'image',
  },
  'course-more': {
    src: '/media/course-more.png',
    w: 1125,
    h: 3300,
    type: 'image',
  },
  placement: {
    src: '/media/placement.png',
    w: 1125,
    h: 2436,
    type: 'image',
  },
  upskilling: {
    src: '/media/upskilling.png',
    w: 1125,
    h: 2436,
    type: 'image',
  },
  stories: {
    src: '/media/stories.png',
    w: 1125,
    h: 2436,
    type: 'image',
  },
  'sheet-course': {
    src: '/media/sheet-course.png',
    w: 1179,
    h: 2556,
    type: 'image',
  },
  'price-dual': {
    src: '/media/price-dual.png',
    w: 1125,
    h: 2442,
    type: 'image',
  },
  'price-trial': {
    src: '/media/price-trial.png',
    w: 1125,
    h: 2442,
    type: 'image',
  },
  'trial-popup': {
    src: '/media/trial-popup.png',
    w: 1125,
    h: 2442,
    type: 'image',
  },
  'pay-success': {
    src: '/media/pay-success.png',
    w: 1179,
    h: 2556,
    type: 'image',
  },
  'pay-failed': {
    src: '/media/pay-failed.png',
    w: 1179,
    h: 2556,
    type: 'image',
  },
  'course-content': {
    src: '/media/course-content.png',
    w: 1125,
    h: 2442,
    type: 'image',
  },
  'course-article': {
    src: '/media/course-article.png',
    w: 1125,
    h: 2442,
    type: 'image',
  },
  'quiz-q': {
    src: '/media/quiz-q.png',
    w: 1125,
    h: 2436,
    type: 'image',
  },
  'quiz-a': {
    src: '/media/quiz-a.png',
    w: 1125,
    h: 2436,
    type: 'image',
  },
  'quiz-done': {
    src: '/media/quiz-done.png',
    w: 1125,
    h: 2436,
    type: 'image',
  },
  nps: {
    src: '/media/nps.png',
    w: 1125,
    h: 2442,
    type: 'image',
  },
  'search-min': {
    src: '/media/search-min.png',
    w: 1125,
    h: 2700,
    type: 'image',
  },
  'search-results': {
    src: '/media/search-results.png',
    w: 1125,
    h: 2700,
    type: 'image',
  },
  'search-empty-v1': {
    src: '/media/search-empty-v1.png',
    w: 1125,
    h: 2700,
    type: 'image',
  },
  'search-empty-v2': {
    src: '/media/search-empty-v2.png',
    w: 1125,
    h: 2700,
    type: 'image',
  },
  profile: {
    src: '/media/profile.png',
    w: 1125,
    h: 2433,
    type: 'image',
  },
  'profile-paid': {
    src: '/media/profile-paid.png',
    w: 1125,
    h: 2442,
    type: 'image',
  },
  'profile-unpaid': {
    src: '/media/profile-unpaid.png',
    w: 1125,
    h: 2442,
    type: 'image',
  },
  'profile-avatar': {
    src: '/media/profile-avatar.png',
    w: 1125,
    h: 2436,
    type: 'image',
  },
  'upd-hard': {
    src: '/media/upd-hard.png',
    w: 1125,
    h: 2436,
    type: 'image',
  },
  'upd-hard-v2': {
    src: '/media/upd-hard-v2.png',
    w: 1125,
    h: 2436,
    type: 'image',
  },
  'upd-soft': {
    src: '/media/upd-soft.png',
    w: 1125,
    h: 2448,
    type: 'image',
  },
  'upd-maint': {
    src: '/media/upd-maint.png',
    w: 1125,
    h: 2436,
    type: 'image',
  },
  'store-01': {
    src: '/media/store-01.png',
    w: 927,
    h: 2132,
    type: 'image',
  },
  'store-02': {
    src: '/media/store-02.png',
    w: 927,
    h: 2132,
    type: 'image',
  },
  'store-03': {
    src: '/media/store-03.png',
    w: 927,
    h: 2132,
    type: 'image',
  },
  'store-04': {
    src: '/media/store-04.png',
    w: 927,
    h: 2132,
    type: 'image',
  },
  'store-05': {
    src: '/media/store-05.png',
    w: 927,
    h: 2132,
    type: 'image',
  },
  'store-06': {
    src: '/media/store-06.png',
    w: 927,
    h: 2132,
    type: 'image',
  },
  'store-07': {
    src: '/media/store-07.png',
    w: 1197,
    h: 2130,
    type: 'image',
  },
  'store-08': {
    src: '/media/store-08.png',
    w: 1197,
    h: 2130,
    type: 'image',
  },
  'store-09': {
    src: '/media/store-09.png',
    w: 1197,
    h: 2130,
    type: 'image',
  },
  'store-10': {
    src: '/media/store-10.png',
    w: 1197,
    h: 2130,
    type: 'image',
  },
  'store-11': {
    src: '/media/store-11.png',
    w: 1197,
    h: 2130,
    type: 'image',
  },
  'store-12': {
    src: '/media/store-12.png',
    w: 1197,
    h: 2130,
    type: 'image',
  },
  'store-13': {
    src: '/media/store-13.png',
    w: 1197,
    h: 2130,
    type: 'image',
  },
  'v-sheet': {
    src: '/media/v-sheet.mp4',
    type: 'video',
  },
  'v-coupon': {
    src: '/media/v-coupon.mp4',
    type: 'video',
  },
  'v-exp-final': {
    src: '/media/v-exp-final.mp4',
    type: 'video',
  },
  'v-exp-iter': {
    src: '/media/v-exp-iter.mp4',
    type: 'video',
  },
  'v-splash': {
    src: '/media/v-splash.mp4',
    type: 'video',
  },
  'v-home1': {
    src: '/media/v-home1.mp4',
    type: 'video',
  },
  'v-home2': {
    src: '/media/v-home2.mp4',
    type: 'video',
  },
  'bar-home-unpaid': {
    src: '/media/bar-home-unpaid.png',
    w: 1125,
    h: 250,
    type: 'image',
  },
  'bar-home-paid': {
    src: '/media/bar-home-paid.png',
    w: 1125,
    h: 250,
    type: 'image',
  },
  'bar-experience': {
    src: '/media/bar-experience.png',
    w: 1125,
    h: 250,
    type: 'image',
  },
  'bar-syllabus': {
    src: '/media/bar-syllabus.png',
    w: 1128,
    h: 345,
    type: 'image',
  },
  'bar-price-six': {
    src: '/media/bar-price-six.png',
    w: 1125,
    h: 700,
    type: 'image',
  },
};

const CASE_STUDY_BASE = '/case-studies/prepinsta-app';
for (const asset of Object.values(M))
  asset.src = `${CASE_STUDY_BASE}${asset.src}`;
