// GENERATED by scripts/manifest.mjs — do not hand-edit.
// Re-run after adding or replacing anything in public/media.
export const M = {
  'cert-modal': {
    src: '/media/cert-modal.png',
    w: 900,
    h: 963,
    type: 'image',
  },
  'course-cards': {
    src: '/media/course-cards.png',
    w: 800,
    h: 1045,
    type: 'image',
  },
  'profile-edit': {
    src: '/media/profile-edit.png',
    w: 860,
    h: 1275,
    type: 'image',
  },
  'profile-m-avatar': {
    src: '/media/profile-m-avatar.png',
    w: 750,
    h: 1628,
    type: 'image',
  },
  'profile-m-empty': {
    src: '/media/profile-m-empty.png',
    w: 750,
    h: 1433,
    type: 'image',
  },
  'profile-m-unpaid': {
    src: '/media/profile-m-unpaid.png',
    w: 750,
    h: 2400,
    type: 'image',
  },
  'profile-m-upg': {
    src: '/media/profile-m-upg.png',
    w: 750,
    h: 1628,
    type: 'image',
  },
  'profile-m': {
    src: '/media/profile-m.png',
    w: 750,
    h: 3000,
    type: 'image',
  },
  'profile-web': {
    src: '/media/profile-web.png',
    w: 2176,
    h: 1657,
    type: 'image',
  },
  'purchase-web': {
    src: '/media/purchase-web.png',
    w: 2176,
    h: 17433,
    type: 'image',
  },
  'search-cat': {
    src: '/media/search-cat.png',
    w: 1080,
    h: 1060,
    type: 'image',
  },
  'search-context': {
    src: '/media/search-context.png',
    w: 2176,
    h: 1198,
    type: 'image',
  },
  'search-open': {
    src: '/media/search-open.png',
    w: 1006,
    h: 1031,
    type: 'image',
  },
  'search-results': {
    src: '/media/search-results.png',
    w: 1080,
    h: 1060,
    type: 'image',
  },
  'syllabus-old': {
    src: '/media/syllabus-old.png',
    w: 1100,
    h: 12970,
    type: 'image',
  },
  'syllabus-rail': {
    src: '/media/syllabus-rail.png',
    w: 2176,
    h: 351,
    type: 'image',
  },
  'syllabus-web': {
    src: '/media/syllabus-web.png',
    w: 1100,
    h: 9666,
    type: 'image',
  },
  'toast-call': {
    src: '/media/toast-call.png',
    w: 900,
    h: 590,
    type: 'image',
  },
  'upgrade-open': {
    src: '/media/upgrade-open.png',
    w: 1100,
    h: 950,
    type: 'image',
  },
  'v-learn': {
    src: '/media/v-learn.mp4',
    type: 'video',
  },
  'v-mentor': {
    src: '/media/v-mentor.mp4',
    type: 'video',
  },
  'v-nav': {
    src: '/media/v-nav.mp4',
    type: 'video',
  },
  'v-purchase': {
    src: '/media/v-purchase.mp4',
    type: 'video',
  },
};

const CASE_STUDY_BASE = '/case-studies/prepinsta-web';
for (const asset of Object.values(M))
  asset.src = `${CASE_STUDY_BASE}${asset.src}`;
