export const M = {
  home: { src: '/media/home.png', w: 720, h: 1594, type: 'image' },
  notifications: {
    src: '/media/notifications.png',
    w: 720,
    h: 1594,
    type: 'image',
  },
  calculator: { src: '/media/calculator.png', w: 720, h: 1594, type: 'image' },
  'gold-review': {
    src: '/media/gold-review.png',
    w: 720,
    h: 1594,
    type: 'image',
  },
  'payment-gateway': {
    src: '/media/payment-gateway.png',
    w: 720,
    h: 1594,
    type: 'image',
  },
  'payment-failure': {
    src: '/media/payment-failure.png',
    w: 720,
    h: 1594,
    type: 'image',
  },
  'scheme-economics': {
    src: '/media/scheme-economics.png',
    w: 720,
    h: 1594,
    type: 'image',
  },
  terms: { src: '/media/terms.png', w: 720, h: 1594, type: 'image' },
  'scheme-active': {
    src: '/media/scheme-active.png',
    w: 720,
    h: 1594,
    type: 'image',
  },
  'plan-choice': {
    src: '/media/plan-choice.png',
    w: 720,
    h: 1594,
    type: 'image',
  },
  'custom-plan': {
    src: '/media/custom-plan.png',
    w: 720,
    h: 1594,
    type: 'image',
  },
  'amount-summary': {
    src: '/media/amount-summary.png',
    w: 720,
    h: 1594,
    type: 'image',
  },
  'gold-summary': {
    src: '/media/gold-summary.png',
    w: 720,
    h: 1594,
    type: 'image',
  },
  'high-value': {
    src: '/media/high-value.png',
    w: 720,
    h: 1594,
    type: 'image',
  },
  'high-value-active': {
    src: '/media/high-value-active.png',
    w: 720,
    h: 1594,
    type: 'image',
  },
  explore: { src: '/media/explore.png', w: 720, h: 1594, type: 'image' },
  retailer: { src: '/media/retailer.png', w: 720, h: 1594, type: 'image' },
  reviews: { src: '/media/reviews.png', w: 720, h: 1594, type: 'image' },
  'order-review': {
    src: '/media/order-review.png',
    w: 720,
    h: 1594,
    type: 'image',
  },
  portfolio: { src: '/media/portfolio.png', w: 720, h: 1594, type: 'image' },
  'landing-hero': {
    src: '/media/landing-hero.webp',
    w: 1440,
    h: 749,
    type: 'image',
  },
  'landing-product-story': {
    src: '/media/landing-product-story.webp',
    w: 1440,
    h: 749,
    type: 'image',
  },
  'origin-story': {
    src: '/media/origin-story.webp',
    w: 1440,
    h: 749,
    type: 'image',
  },
  'landing-launch-story': {
    src: '/media/landing-launch-story.webp',
    w: 1440,
    h: 749,
    type: 'image',
  },
  'vinayaka-live': {
    src: '/media/vinayaka-live.jpg',
    w: 1800,
    h: 1100,
    type: 'image',
  },
  'zeltgold-live': {
    src: '/media/zeltgold-live.jpg',
    w: 1800,
    h: 1100,
    type: 'image',
  },
  'store-track': {
    src: '/media/store-track.png',
    w: 272,
    h: 592,
    type: 'image',
  },
  'store-invest': {
    src: '/media/store-invest.png',
    w: 272,
    h: 592,
    type: 'image',
  },
  'store-save': { src: '/media/store-save.png', w: 272, h: 592, type: 'image' },
  'store-redeem': {
    src: '/media/store-redeem.png',
    w: 272,
    h: 592,
    type: 'image',
  },
  'store-nearby': {
    src: '/media/store-nearby.png',
    w: 272,
    h: 592,
    type: 'image',
  },
  'admin-dashboard': {
    src: '/media/admin-dashboard.png',
    w: 1280,
    h: 720,
    type: 'image',
  },
  'admin-ledger': {
    src: '/media/admin-ledger.png',
    w: 1280,
    h: 720,
    type: 'image',
  },
  'vendor-dashboard': {
    src: '/media/vendor-dashboard.png',
    w: 1280,
    h: 720,
    type: 'image',
  },
  'vendor-team': {
    src: '/media/vendor-team.png',
    w: 1280,
    h: 720,
    type: 'image',
  },
  'vendor-redemption-verified': {
    src: '/media/vendor-redemption-verified.png',
    w: 1280,
    h: 720,
    type: 'image',
  },
};

const CASE_STUDY_BASE = '/case-studies/zeltgold';
for (const asset of Object.values(M))
  asset.src = `${CASE_STUDY_BASE}${asset.src}`;
