/**
 * Reads public/media and writes lib/media.js — the id → { src, w, h } map the
 * page renders from. Intrinsic dimensions come out of the PNG header, so
 * next/image never has to guess and nothing shifts on load.
 *
 *   node scripts/manifest.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const dir = path.join(root, 'public', 'media');

/** PNG: width/height are two big-endian uint32s at byte 16 of the IHDR. */
function pngSize(file) {
  const fd = fs.openSync(file, 'r');
  const head = Buffer.alloc(24);
  fs.readSync(fd, head, 0, 24, 0);
  fs.closeSync(fd);
  if (head.toString('ascii', 1, 4) !== 'PNG') return null;
  return { w: head.readUInt32BE(16), h: head.readUInt32BE(20) };
}

const out = {};
for (const name of fs.readdirSync(dir).sort()) {
  const id = name.replace(/\.(png|mp4)$/i, '');
  const src = `/case-studies/prepinsta-web/media/${name}`;
  if (name.endsWith('.mp4')) {
    out[id] = { src, type: 'video' };
  } else if (name.endsWith('.png')) {
    const s = pngSize(path.join(dir, name));
    if (s) out[id] = { src, w: s.w, h: s.h, type: 'image' };
  }
}

const body =
  `// GENERATED by scripts/manifest.mjs — do not hand-edit.\n` +
  `// Re-run after adding or replacing anything in public/media.\n` +
  `export const M = ${JSON.stringify(out, null, 2)};\n`;

fs.writeFileSync(path.join(root, 'lib', 'media.js'), body);
console.log(`lib/media.js — ${Object.keys(out).length} assets`);
